/*
NCX Infra Controller REST API

NCX Infra Controller REST API allows users to create and manage resources e.g. VPC, Subnets, Instances across all connected NCX Infra Controller datacenters, also referred to as Sites.

API version: 1.4.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the IpxeTemplateParameter type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IpxeTemplateParameter{}

// IpxeTemplateParameter A key-value parameter passed to an iPXE template for variable substitution
type IpxeTemplateParameter struct {
	// Parameter name referenced in the iPXE template
	Name string `json:"name"`
	// Parameter value substituted into the iPXE template
	Value string `json:"value"`
}

type _IpxeTemplateParameter IpxeTemplateParameter

// NewIpxeTemplateParameter instantiates a new IpxeTemplateParameter object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIpxeTemplateParameter(name string, value string) *IpxeTemplateParameter {
	this := IpxeTemplateParameter{}
	this.Name = name
	this.Value = value
	return &this
}

// NewIpxeTemplateParameterWithDefaults instantiates a new IpxeTemplateParameter object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIpxeTemplateParameterWithDefaults() *IpxeTemplateParameter {
	this := IpxeTemplateParameter{}
	return &this
}

// GetName returns the Name field value
func (o *IpxeTemplateParameter) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *IpxeTemplateParameter) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *IpxeTemplateParameter) SetName(v string) {
	o.Name = v
}

// GetValue returns the Value field value
func (o *IpxeTemplateParameter) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *IpxeTemplateParameter) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *IpxeTemplateParameter) SetValue(v string) {
	o.Value = v
}

func (o IpxeTemplateParameter) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IpxeTemplateParameter) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["value"] = o.Value
	return toSerialize, nil
}

func (o *IpxeTemplateParameter) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varIpxeTemplateParameter := _IpxeTemplateParameter{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varIpxeTemplateParameter)

	if err != nil {
		return err
	}

	*o = IpxeTemplateParameter(varIpxeTemplateParameter)

	return err
}

type NullableIpxeTemplateParameter struct {
	value *IpxeTemplateParameter
	isSet bool
}

func (v NullableIpxeTemplateParameter) Get() *IpxeTemplateParameter {
	return v.value
}

func (v *NullableIpxeTemplateParameter) Set(val *IpxeTemplateParameter) {
	v.value = val
	v.isSet = true
}

func (v NullableIpxeTemplateParameter) IsSet() bool {
	return v.isSet
}

func (v *NullableIpxeTemplateParameter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIpxeTemplateParameter(val *IpxeTemplateParameter) *NullableIpxeTemplateParameter {
	return &NullableIpxeTemplateParameter{value: val, isSet: true}
}

func (v NullableIpxeTemplateParameter) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIpxeTemplateParameter) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
